### ISSUE TITLE
New Device Update Available! Message

### ISSUE THREAD

**Issue by ghost** [tonesto7/nest-manager#351]
After updating to the newest version, I get the following message:  New Device Update Available! Message

I tried uninstalled the app, refreshing the device handlers, and smart app repo - but no luck.

I am thinking this is a new bug?

**Comment by tonesto7** [comment]
What device or devices is the message referring too as having an update?

**Comment by ghost** [comment]
Not sure but here's what I am seeing in the phone.

I uninstall the app, etc.  still same error.

[image1.PNG]

[image2.PNG]

Sent from my iPhone

On Sep 10, 2016, at 5:23 PM, Tonesto7 <notifications@github.com<mailto:notifications@github.com>> wrote:

What device or devices is the message referring too as having an update?

##

**Comment by tonesto7** [comment]
If it's a version issue I likely can resolve it from my end by updating the apps parameters file

**Comment by tonesto7** [comment]
i've verified that the version info is correct.  This has to be an issue with your install.  We have 1500+ installs and you are the only user seeing this issue.  

Here is a list of the version numbers:
- Manager App: 3.1.2
-             thermostat: 3.1.1
-             vthermostat: 3.1.1
-             protect: 3.1.0  
-             camera: 1.1.1
-             presence: 3.1.0, 
-             weather: 3.1.1

Please verify that all of your version numbers match those and are correctly published

**Comment by tonesto7** [comment]
Closing this as the issue should be resolved

**Comment by codahq** [comment]
I'm experiencing this as well as of last night.  I haven't changed anything for weeks.  I don't see any updates on the repo.  I did not see it until last night but it has happened twice since then.

*edit: Very interesting.  It seems that the github integration on the ST API site is not real-time.  Or at least does not sync changes sometimes.  I tried logging out, forcing a cache refresh, etc. and now I'm shown that many of the device handlers were updated.  I imagine that once I update and publish I will be on solid ground again.

**Comment by imnotbob** [comment]
Let us know if you are able to resolve this

**Comment by codahq** [comment]
Yes, I was able to resolve it by updating.  I apologize for the false alarm.  I had never updated somebody else's repository through the github integration and I did not realize there could be a delay before the ST API website showed that changes had been made in the repository.  Keep the issue closed.
