### ISSUE TITLE
Pathlight function on Nest Protect no longer working

### ISSUE THREAD

**Issue by kevinwestby** [tonesto7/nest-manager#394]
Has anyone else reported the Nest Protect path light function no longer working?

Since setting this up, mine is no longer working....even though it is enabled within the core Next application on my iPhone.

**Comment by tonesto7** [comment]
Yea this must just be a coincidence because pathlight is not expose to the Works with Nest api.  We have no way to control or even see the pathlight status.

**Comment by kevinwestby** [comment]
Ok, thanks!


Kevin Westby, CISSP, CCSP, CIPT
(319) 795-0420
kevin@kevinwestby.com<mailto:kevin@kevinwestby.com>
http://www.westbydigitalmedia.com

Take pictures…in 20 years, you’ll be glad you did.

**Comment by kevinwestby** [comment]
ok, thanks!

**Comment by kevinwestby** [comment]
So, could anything in the custom device type be causing this issue?  I’ve reset the Nest, removed the batteries and it’s still not working.  I also have a friend who is having the same issue

**Comment by imnotbob** [comment]
Not that we are aware of.  Again we make no commands to the protect, nor do we have api access to any protect features.

I would suggest you should work with Nest support so they can determine what is going on.

I would suggest initially not getting into ST with them, and just have them assess why it is not working, and if you have a problem with your unit.

**Comment by kpdillon** [comment]
I don't think this is coincidence.  I recently just installed this Nest Manager and my Path light is no longer functioning either!  It had been working fine previously.  Maybe some kind of query to the nest API online is causing this issue?

**Comment by imnotbob** [comment]
We don't know what is causing your issue.  If you want to test by turning off Nest manager, that would be a test to prove your theory.

We have not changed our API calls.  We log our calls in the IDE log.  

We don't think we are causing your issue.

**Comment by kpdillon** [comment]
Gotcha.  I did find this.  I'll do some more testing.

What is Pathlight?

Affected products: Nest Protect
Pathlight lights your way in the dark. Pathlight briefly turns on when you walk under your Nest Protect, then turns off again after you pass by. If you have a wired Nest Protect, Pathlight can also be set to stay on whenever it’s dark in the room.

With Pathlight, you don't need to stumble around in the dark, use your smartphone as a flashlight, or keep a night light on all the time. Pathlight is like a night light that only turns on when it's dark. It's ideal for hallways, the kid's room or any location in your home where you'd like a bit of extra light.

To light your way, Pathlight uses high efficiency LEDs set for low brightness, so it's easy on your batteries and won't waste energy. Even when it's set to Always-on, Pathlight consumes much less energy than typical incandescent bulbs. The long-life LEDs have been rated to exceed Nest Protect's product lifetime (7 years for 1st gen Nest Protect, 10 years for 2nd gen), so Pathlight will work for as long as your Nest Protect does.

To preserve battery life, Pathlight has been optimized differently for wired and battery powered Nest Protects. Here are the differences between them:

Nest Protect
How it works
Battery
On: Pathlight will turn on for about 5 seconds as you pass by.
Wired
On: Pathlight will turn on for about 10 seconds as you pass by. 
Always on: If you choose "Always On", Pathlight will turn on when it gets dark, and turn off when the room brightens up: so you don't have to walk by to turn it on. This option is great for a kid's room or a dark area like a stairwell.

Can I disable Pathlight?

Yes, you can switch Pathlight off with the Nest app to save battery life or if you want the room to stay dark. Pathlight is off by default for Nest Protects installed in bedrooms.

1. Open the Nest Protect icon on the home screen.

2. Select the Settings icon in the top right corner of the screen (it's shaped like a gear).

3. Pick the Nest Protect you want to change settings for.

4. Tap Nest Sense.

5. Tap Pathlight.

6. If you have battery powered Nest Protect, select Pathlight and flip the switch to turn it on or off.

If you have a wired Nest Protect, you can choose if you want Pathlight off, on, or always on.

Note: Your Pathlight change will take effect within a day for a battery powered Nest Protect and within an hour for a wired Nest Protect. (You'll see a clock icon in the app to indicate the pending change.) To update Pathlight immediately, press the Nest button once on your Nest Protect.

Pathlight on 2nd gen Nest Protects

Pathlight is even better on the 2nd gen Nest Protect. The redesigned light ring has an additional LED, so the brightest setting is even brighter, and the medium setting uses less battery power for the same light output. In addition, you'll notice that Pathlight will turn on quicker as you walk underneath your Nest Protect.

Even though I've turned out the lights, Pathlight hasn't turned on. Why?

Pathlight is designed to turn on in dark rooms or hallways. If there's enough light to see, Pathlight generally won't turn on.

It takes a little while for your eyes to get accustomed to a darkened room, so we designed Pathlight to turn on only when the room has been dark for a little while. The delay is usually just a few seconds. That's why you may not see Pathlight immediately after you see a green or yellow Nightly Promise light.

When Nest Protect's batteries are very low, you'll get a notification in the Nest app, Nightly Promise will glow yellow, and Pathlight will be disabled automatically. That way, Nest Protect can extend your battery life and keep protecting you as long as it can.

How do I set Pathlight brightness?

**Comment by kevinwestby** [comment]
“Problem” solved!!  I had some Xmas lights on my stairs that I never would have thought would have impacted this....turned them off, and path light started working again.  

Thanks for you very prompt responses on this....love the integration this provides!!
