### ISSUE TITLE
Nest Cam capabilities disabled

### ISSUE THREAD

**Issue by jterrace** [tonesto7/nest-manager#398]
I was trying to figure out why the nest cam devices are not working with SmartTiles. What I found is that the camera-related capabilities are disabled:

		//capability "Image Capture"
		//capability "Video Camera"
		//capability "Video Capture"
https://github.com/tonesto7/nest-manager/blob/master/devicetypes/tonesto7/nest-camera.src/nest-camera.groovy#L36

Looks like Image Capture was disabled in f33bdd04a299cb2db4066661f4ae5271b0acab3b Was that intentional? If so, why?

**Comment by tonesto7** [comment]
Because the nest cam streaming is a hack.  It uses its own special protocols. Which would be difficult to support in other smart apps. I disabled those because they are useless at the moment.  I will look into the requirements to getting it working with smart tiles (if it's possible)  
Currently the hack that allowed us to get the streaming in the device handler is broken which is what I'm working on currently

**Comment by jterrace** [comment]
I see, thanks. I was able to use a workaround with SmartTiles to get the cameras working (bypassing the device):
http://www.smarttiles.click/help/#Dropcam_Nest_Cam_Stop_Motion_Video_Stream

**Comment by tonesto7** [comment]
Image Capture and Video Camera are now active in v2.4.0 of the camera device
