### ISSUE TITLE
Feature Request: Add Humidity Control and Automation

### ISSUE THREAD

**Issue by jdc0730** [tonesto7/nest-manager#407]
## Verify the following before opening an issue:

- [ ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [ ] The SmartApp and Device are using the latest version.
- [ ] You have reviewed the Readme for potential fixes.
- [ ] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects? 4
* Are you Using the Nest Presence Device? No
* iOS or Android?: iOS
* Mobile App Version: 10.2

## Expected Behavior
I would like the ability to control the humidity from Nest Manager. Ideally, there would be an automation that would set the humidity based on the outside temperature (http://www.rmsab.com/articles/proper-indoor-humidity/). More flexibility could be added by allowing the user to add an adjustment (+ or -) and using a formula like (Outside Temp * 0.5 + 25 - Adjustment).

## Current Behavior
Currently, no way to set humidity.

## Context
I had previously used this (https://github.com/desertblade/device-type.nest/blob/With-Humidity-Controls/nest.devicetype.groovy) device type along with this (https://github.com/bmmiller/SmartThings/blob/master/smartapps/bmmiller/humidity-reset-schedule.src/humidity-reset-schedule.groovy) SmartApp to make adjustments to the humidity levels in order to control condensation in my home.

**Comment by compmas2** [comment]
I would also love to see this feature implemented.  Additionally the Nest thermostat has a setting for times during the day when the humidifier should not run and it would be great it that can be controlled too.

**Comment by tonesto7** [comment]
The official API from desertblade was using a hack which emulated the Nest iOS mobile app which has access to the full controls used in the mobile app

**Comment by tonesto7** [comment]
We are using the official API which does not allow access to control humidity.

**Comment by imnotbob** [comment]
Good ideas.

Few questions:

a)  I assume you want us to "control" a switch (or set of switches) to turn on / off humidifier?   I ask as I don't think Nest gives us api control to a humidifier it is controlling.  (i.e. this is an external humidifier on its own smart switch/outlet)

Above is "adding humidity"

b)  The other question is are you looking for something for drying?  i.e. run the AC system some ?  Nest has the build in cool-to-dry,  but we have no api access to it...you can set it in your Nest, and it will just do its thing...

or is this like a) except turning on/off a dehumidifier that is on a switch?


This is "removing humidity"


FYI, I do a) right now, but it does require me to have other smartapps like CoRE.   I like the idea of building this in, just trying to understand what controls have to be there.

**Comment by jdc0730** [comment]
@imnotbob I am not sure I completely understand your question. I have a whole house humidifier that is controlled by the Nest. So what I was looking for was simply a way to set the humidity value on the Nest which @tonesto7 is indicating isn't possible (unfortunately). We have gas heat so it's generally a matter of not having the humidifier turn on as the gas heat tends to dry things out.

**Comment by imnotbob** [comment]
You are correct - what I describe is not what you want.

Tony is correct that the Nest API does not let us set humidity level.  You can do this thru your Nest mobile or Nest web app.    We are working to get Nest certification, so we cannot go outside Nest's published APIs.

Do you find you change your humidity setting regularly in Nest?   I get the impression they left it out of their API perhaps because they believe it is set-it and forget-it...


In my case, I have external humidifiers (Venta), and putting them on a smartswitch let's me turn them on/off based on home/away, outdoor temp, and humidity level.   This type of automation could be put in Nest Manager.

**Comment by compmas2** [comment]
I personally change the humidity level often in the winter.  I live in a cold area and the article referenced in the original request shows the proper humidity level for outside temperatures.  If the humidity is too high, condensation forms on all my windows and around doorways.  Instead of having manually adjust it each day based on the outside temperature it would great to automate the adjustments.

**Comment by imnotbob** [comment]
If you decide to reach out to Nest, do encourage them to allow setting humidity setting via API.

**Comment by jdc0730** [comment]
@imnotbob My use is similar to @compmas2. The temperature changes here frequently here so I do adjust it almost daily. I've taken the old device code and stripped out everything that wasn't dealing with humidity and installed it as another device. That should work for the time being.

**Comment by imnotbob** [comment]
I Would be interested in seeing your code.

**Comment by jdc0730** [comment]
@imnotbob I spent very, VERY little time on it. It is very easy to overload the API by rapidly adjusting the humidity. I don't ever do this, relying instead on the SmartApp to make the adjustment which works fine. All those caveats in place:

https://github.com/jdc0730/device-type.nest-humidity/blob/master/devicetypes/jdc0730/nest-humidity-control.src/nest-humidity-control.groovy

**Comment by imnotbob** [comment]
A thought that may help you on the commands, is instead of doing up/down by one (forcing a lot of commands), you just send a setHumidityLevel(nn), so you can make a change as a single command?

That would mean perhaps removing the up / down commands?

**Comment by imnotbob** [comment]
@jdc0730 , @compmas2 
Can y'all contact me on ST forums - via a private message?  I have a few things to ask.

**Comment by tonesto7** [comment]
This should be good as it was added to v5.0

**Comment by compmas2** [comment]
I see this was added but it looks like it only turns on or off the humidifier functionality.  Does Nest still not expose the adjustment of what humidity level to set since that is what needs to be regularly adjusted during Winter months.

Thanks for the addition though since that will at least allow me to regulate my house from over humidifying by cycling it on and off periodically.

**Comment by tonesto7** [comment]
I really wish Nest would allow control of humidity using the API.
This works with the https://github.com/jdc0730/device-type.nest-humidity ;)

**Comment by imnotbob** [comment]
The automation now in NST manager does adjust the desired humidity setting based on outside temps.

This is described in:  http://thingsthataresmart.wiki/index.php?title=NST_Manager#Humidifier_Control
