### ISSUE TITLE
Direct Alexa integration no longer works "multiple devices"

### ISSUE THREAD

**Issue by neocody** [tonesto7/nest-manager#420]
So the direct Alexa integration I have setup seems to no longer work. Every time I give it a command it says multiple devices exist. When I check there is indeed the Nest thermostat listed twice, one through SmartThings and the other directly through Alexa. Whenever I remove the ST Nest in Alexa, it works until the discovery re-adds it. I tried changing the device name of the nest inside ST however it seems it changes back to the actual name of the Nest thermostat. I know the voice activation is not yet inside Nest Manager so wondering how can I work around this, preferably would like to keep the Nest thermostat in ST but still be able to use the Nest integration with Alexa?

**Comment by tonesto7** [comment]
I guess I'm confused 😐 

What exactly is the issue?
If it's listed twice in Alexa it's because the thermostat is selected under the amazon Echo smart app.  

Have you tried Ask Alexa smart app?  It is far more powerful than the official Echo integration. 

http://thingsthataresmart.wiki/index.php?title=Ask_Alexa
