### ISSUE TITLE
This device is unavailable

### ISSUE THREAD

**Issue by RonRamsey** [tonesto7/nest-manager#429]
Have been using your code for over a year and has been working great.  Updated to 5.0 this morning and smartthings reports device unavailable.  I only updated and published the code you posted.  Nothing else was changed.  All are newest updates, OAuth is enabled.  One thermostat, four protect, have present installed but not utilizing.  looked thought readme but no help.  Still says ver 4.5.2 in app and will not update to 5.

## Verify the following before opening an issue:

- [ ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [ ] The SmartApp and Device are using the latest version.
- [ ] You have reviewed the Readme for potential fixes.
- [ ] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?:
* How many Protects?
* Are you Using the Nest Presence Device?
* iOS or Android?:
* Mobile App Version:

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Please include a copy of your log under the IDE if possible>>>

**Comment by imnotbob** [comment]
Sorry for your trouble.  I suggest you review that everything is installed properly per the new instructions, and then you share IDE logs with us.

You should share the IDE logs via  private message in the community, as posting here is "for all to see".
http://thingsthataresmart.wiki/index.php?title=NST_Manager

**Comment by jdigangi** [comment]
I am having the same issue one of my theromostats show offline and one protect.

**Comment by jdigangi** [comment]
I enabled logging and shared the code, you guys have done a terrific job with this app.  Anything I can do to help debug drop me a line

**Comment by jdigangi** [comment]
Btw turn off device health and all sensors that were not reporting suddenly do, perhaps this is a ST issue with the hub code

**Comment by mburrough** [comment]
Same issue - disabled device health and now my thermostat and presence devices show as online.

**Comment by tonesto7** [comment]
The issue is actually with ST. 
The device health is actually on a different system at st.  At some point that system gets out of sync with ST and shows offline.  

In all of the latest versions of Our device code there is a repair system.  This will normally only fire on device version updates but can be manually run by entering the device UI and pressing the gear top right corner and then press done.

**Comment by jdigangi** [comment]
I agree with you, great app btw. I shut off device heath even my ST water sensor started working again.

Thanks!!!

Thanks,

James A. DiGangi
516.662.2222 Cellular

On Apr 11, 2017, at 7:40 AM, Tonesto7 <notifications@github.com<mailto:notifications@github.com>> wrote:


The issue is actually with ST.
The device health is actually on a different system at st. At some point that system gets out of sync with ST and shows offline.

In all of the latest versions of Our device code there is a repair system. This will normally only fire on device version updates but can be manually run by entering the device UI and pressing the gear top right corner and then press done.

**Comment by FelipeSeiber** [comment]
Just wanted to say I was having the same issue. I entered the device UI and pressed the gear top right corner and then pressed done and it resolved the issue. Just wanted to note it here as well for others. 

Great app, really great work!

Thanks,

**Comment by jdigangi** [comment]
Felipe 

Your workaround appears to work like a charm! Thank you

James

**Comment by bgibson710** [comment]
I agree with jdigangi and FelipeSeiber.  I have device health turned on, it showed my thermostat as unavailable, I went into the device UI hit the gear icon and hit done and everything looks good.
