### ISSUE TITLE
Beware: App Updates = Hours Spent Fixing Offline Devices = Smartapp not recommended. Despite seeing many updates, even functionality to ensure the offline issue doesn't happen, I've probably spent 15h on this app to accommodate the terrible UX and the pain isn't worth the benefit in most cases. Just go without for now.

### ISSUE THREAD

**Issue by tysonmiller** [tonesto7/nest-manager#434]
## Verify the following before opening an issue:

- [ ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [ ] The SmartApp and Device are using the latest version.
- [ ] You have reviewed the Readme for potential fixes.
- [ ] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?:
* How many Protects?
* Are you Using the Nest Presence Device?
* iOS or Android?:
* Mobile App Version:

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Please include a copy of your log under the IDE if possible>>>

**Comment by compmas2** [comment]
I encountered a large number of errors too,  These errors occurred when I upgraded from 4.5.1 and also after deleting everything related to nest-manager and adding back version 5.0.3,  These errors included:
- NST Automation items showing up under SmartApps section that had nothing but a remove button that did not work.  To remove these I had to go through the IDE -> My Locations -> Location Name -> List SmartApps and manually uninstall all bad instances.
- Sometimes Automations I added would show up under SmartApps and sometimes not.
- I could never get all my devices to show up without a couple not connecting ever.  It seems random which devices won't connect.

**Comment by tonesto7** [comment]
@Tysonmiller
That's interesting that it's a terrible app and ux.  
Maybe next time you should read the directions.   

###Updates have only been tested from 4.5.2 and up.  
Really 15hours.  I've spend 3000-4000 hours developing this crap for a unpredictable platform.  


So why don't you maybe act a bit more respectful next time.  It would be helpful to both of us if you try reaching out to the people who made it instead of posting a comment like this on Github.
We can't fix what we can't see or duplicate. 

The offline issue was a bug in st health system.  I spent 2 days straight working with SmartThings to get a fix. 
I would have worked with you to personally got your setup working and maybe found the bug/bugs causing your issues.
