### ISSUE TITLE
you are not authorised to perform the requested operation install and configure issue

### ISSUE THREAD

**Issue by serlef** [tonesto7/nest-manager#441]
## Verify the following before opening an issue:

- [ x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [ x] The SmartApp and Device are using the latest version.
- [ x] You have reviewed the Readme for potential fixes.
- [ x] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 0
* How many Protects? 2
* Are you Using the Nest Presence Device? no
* iOS or Android?: iOS
* Mobile App Version: 2.3.0

## Expected Behavior
 expect to be able to complete setup successfully.

## Current Behavior
I am trying to install nest manager, I can add the smart app, authenticate to nest, see my device and select it, when I get tot eh end of the setup I get a green banner saying Nest manager is installed and automating, then immediately after that I get a red banner stating that "you are not authorised to perform the requested operation" can't get any further than that, checked oath is enabled, published app ok, tried removing and rebooting hub, nothing works, bit stumped.

## Steps to Reproduce (for bugs)

1. happened on every attempt to setup
2.
3.
4.

## Context
 can't complete setup

Please include a copy of your log under the IDE if possible>>>

**Comment by tonesto7** [comment]
I've seen this before.  Just don't know where it's coming from.  
Can you have the logs running when you try again?  I'm hoping it's throwing an exception

**Comment by youhorns** [comment]
Hi I have exactly the same problem and set up as serlef, only difference is that I have one nest thermostat and one protect. Has anything been found to resolve this. Thanks

**Comment by youhorns** [comment]
Happy days just went through the whole process again and it installed ok . I must have missed something off last time .

**Comment by mjnewham** [comment]
I'm also getting this issue. It was working, and I updated the Manager, and a number of Device Handlers. Rather than coming up with 'Home' (my hub), it came up with an obscure ID and didn't show my protect devices.

Removed the app from ST, reinstalled from "My Apps" and I keep getting the ... not authorised ... message/banner. Killed the app from IDE and reinstalled (incl. OAuth) same thing. 

Any assistance would be appreciated.

**Comment by imnotbob** [comment]
Can you share IDE logs when you doing the issue?   You do this by logging into the IDE,

then select the tab "live logging"   

Leave that browser window open, then do you test/failure.

Send us the IDE logs (cut and paste) in private message in the forums (so they are not as publicly posted here)

**Comment by mjnewham** [comment]
This is new to me, where is the forum so I can post it to you?

**Comment by mjnewham** [comment]
Additionally--this might help--If I install Nest Manager from within the ST App, authenticate with Nest, select my 'home' (next), enter iOS for the Mobile Device, but don't select any devices I still get the error when I click done.

**Comment by mjnewham** [comment]
I'm watching Live logging and nothing is coming up... just have "Waiting for events..."

**Comment by imnotbob** [comment]
In the community forum, you can post private message by clicking on the circle in the upper right that likely has the first letter of your name;   Then click on the mail icon near the top of the popup / fly over.

Be sure you have looked at the docs.   http://thingsthataresmart.wiki/index.php?title=NST_Manager

My speculation is you may be having issues with logging into the correct shard.   This is a confusing part of smartthings, but you need to login to the right place, and install in the right place.   If you are still unsure if you are in the right shard, SmartThings support is good about helping you with that portion.

Otherwise ensure all the steps were followed in the install (in the right shard), and then you can post us IDE logs.   Seeing nothing in the logs suggests "wrong shard".

**Comment by tonesto7** [comment]
closing issue
