### ISSUE TITLE
I would like to change temperature setting from F to C AFTER installation.. can't find a place to do that?

### ISSUE THREAD

**Issue by LeisureL** [tonesto7/nest-manager#449]
## Verify the following before opening an issue:

- [ ] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [ ] The SmartApp and Device are using the latest version.
- [ ] You have reviewed the Readme for potential fixes.
- [ ] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?:
* How many Protects?
* Are you Using the Nest Presence Device?
* iOS or Android?:
* Mobile App Version:

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Please include a copy of your log under the IDE if possible>>>

**Comment by imnotbob** [comment]
The C or F setting is done in your Smartthings account.

Open the SmartThings Mobile App:
Confirm location is setup correctly
go to three horizontal bars (lower right)
go to select a location, and select settings (gear in upper right)
ensure the Temperature scale is set correct, and hit "Done"

Note that when using C mode, some device handlers (weather, thermostat) may not display all colors correctly due to a SmartThings limitation that device handler UIs cannot be set at run time.

There are instructions in the docs how to deal with the colors:
http://thingsthataresmart.wiki/index.php?title=NST_Manager#Things_to_Know

**Comment by LeisureL** [comment]
Thanks worked like a charm
