### ISSUE TITLE
Out of tokens?

### ISSUE THREAD

**Issue by greghesp** [tonesto7/nest-manager#69]
I have a feeling you might be out of tokens.

Every time I open the app and try to use it, I get the following:

> 11:25:06 AM: warn Your Nest Token has been revoked successfully...
> 11:24:13 AM: debug AuthToken not found: Directing to Login Page...

**Comment by tonesto7** [comment]
i'm not out of tokens.  I'm only using 280 of the 1000.

The only was a token is revoked in smartapp is to initiate an Uninstall or runing the logout withing Nest Manager

**Comment by greghesp** [comment]
Hmm, potentially a bug then?  Is it normal to have to authorise with Nest, every time I want to use the app?
I seem to have duplicates of everything, possibly due to this

**Comment by tonesto7** [comment]
If you didn't have oauth enabled when you tried to install it will create duplicates.  The auth only happens if the token doesn't exist.  And the only way it doesn't exist is if you tried to uninstall and it failed to remove the app/devices or the logout was pressed under preferences. < Those are the only way  

version 2.0 will be out very soon and all of this stuff shouldn't happen any more.

**Comment by greghesp** [comment]
Hmmm OK odd.  I did forget to turn on OAuth, however I've since turned it on and I still get kicked out. 
I'll remove it all and try again.

Is the dev branch updated with the latest code, or has it not all been committed?

EDIT:  Can't removed because installed on my girlfriends phone too.  Grrrrrrr - SmartThings!!

**Comment by tonesto7** [comment]
You will need to uninstall the app(s) and start over.  If Oauth wasn't active on the apps first run it screws up the application states.

Please DO NOT use the dev code yet... it not complete yet.
